USE [master]
GO

IF EXISTS(select * from sys.databases where name='Seggu')
DROP DATABASE Seggu

CREATE DATABASE [Seggu]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Seggu', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\Seggu.mdf' , SIZE = 81920KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Seggu_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\Seggu_log.ldf' , SIZE = 353216KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Seggu] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Seggu].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Seggu] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Seggu] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Seggu] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Seggu] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Seggu] SET ARITHABORT OFF 
GO

ALTER DATABASE [Seggu] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Seggu] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Seggu] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Seggu] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Seggu] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Seggu] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Seggu] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Seggu] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Seggu] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Seggu] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Seggu] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Seggu] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Seggu] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Seggu] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Seggu] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Seggu] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Seggu] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Seggu] SET RECOVERY FULL 
GO

ALTER DATABASE [Seggu] SET  MULTI_USER 
GO

ALTER DATABASE [Seggu] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Seggu] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Seggu] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Seggu] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

-- ALTER DATABASE [Seggu] SET DELAYED_DURABILITY = DISABLED 
-- GO

ALTER DATABASE [Seggu] SET  READ_WRITE 
GO

USE [master]
GO

IF EXISTS (SELECT * FROM sys.syslogins WHERE name = N'seggu') 
DROP LOGIN [seggu]
GO

CREATE LOGIN [seggu] WITH PASSWORD=N'seggu', DEFAULT_DATABASE=[Seggu], CHECK_EXPIRATION=OFF, CHECK_POLICY=ON
GO
USE [Seggu]
GO
CREATE USER [seggu] FOR LOGIN [seggu]
GO
USE [Seggu]
GO
ALTER USER [seggu] WITH DEFAULT_SCHEMA=[dbo]
GO
USE [Seggu]
GO
ALTER ROLE [db_owner] ADD MEMBER [seggu]
GO

