//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seggu.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accessory
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Stamp { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public System.Guid AccessoryTypeId { get; set; }
        public decimal Value { get; set; }
        public System.Guid VehicleId { get; set; }
    
        public virtual AccessoryType AccessoryType { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
