//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seggu.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public System.Guid Id { get; set; }
        public string Street { get; set; }
        public string Phone { get; set; }
        public string Number { get; set; }
        public string Floor { get; set; }
        public string Appartment { get; set; }
        public Nullable<System.Guid> LocalityId { get; set; }
        public string PostalCode { get; set; }
        public AddressType AddressType { get; set; }
        public Nullable<System.Guid> ClientId { get; set; }
    
        public virtual Locality Locality { get; set; }
        public virtual Client Client { get; set; }
        public virtual Integral Integral { get; set; }
    }
}
