//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seggu.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset
    {
        public Asset()
        {
            this.CashAccounts = new HashSet<CashAccount>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public decimal Amount { get; set; }
    
        public virtual ICollection<CashAccount> CashAccounts { get; set; }
    }
}
