//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seggu.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttachedFile
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> EndorseId { get; set; }
        public string FilePath { get; set; }
        public Nullable<System.Guid> PolicyId { get; set; }
        public Nullable<System.Guid> CasualtyId { get; set; }
        public Nullable<System.Guid> CashAccountId { get; set; }
    
        public virtual Endorse Endorse { get; set; }
        public virtual Policy Policy { get; set; }
        public virtual Casualty Casualty { get; set; }
        public virtual CashAccount CashAccount { get; set; }
    }
}
