//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seggu.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank
    {
        public Bank()
        {
            this.ClientCreditCards = new HashSet<ClientCreditCard>();
            this.Cheques = new HashSet<Cheque>();
        }
    
        public System.Guid Id { get; set; }
        public string Number { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<ClientCreditCard> ClientCreditCards { get; set; }
        public virtual ICollection<Cheque> Cheques { get; set; }
    }
}
