//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seggu.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashAccount
    {
        public CashAccount()
        {
            this.AttachedFiles = new HashSet<AttachedFile>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid AssetId { get; set; }
        public System.Guid LedgerAccountId { get; set; }
        public System.DateTime Date { get; set; }
        public string Description { get; set; }
        public decimal Amount { get; set; }
        public decimal Balance { get; set; }
        public System.Guid ProducerId { get; set; }
        public Nullable<System.Guid> FeeId { get; set; }
        public string ReceiptNumber { get; set; }
    
        public virtual LedgerAccount LedgerAccount { get; set; }
        public virtual Producer Producer { get; set; }
        public virtual Asset Asset { get; set; }
        public virtual Fee Fee { get; set; }
        public virtual ICollection<AttachedFile> AttachedFiles { get; set; }
    }
}
