//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seggu.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientCreditCard
    {
        public System.Guid Id { get; set; }
        public Nullable<long> Number { get; set; }
        public System.Guid ClientId { get; set; }
        public System.Guid CreditCardId { get; set; }
        public System.Guid BankId { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual CreditCard CreditCard { get; set; }
        public virtual Bank Bank { get; set; }
    }
}
