//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seggu.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.ProducerCodes = new HashSet<ProducerCode>();
            this.CreditCards = new HashSet<CreditCard>();
            this.Contacts = new HashSet<Contact>();
            this.Risks = new HashSet<Risk>();
            this.Liquidations = new HashSet<Liquidation>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Notes { get; set; }
        public bool Active { get; set; }
        public string EMail { get; set; }
        public string CUIT { get; set; }
        public Nullable<short> LiqDay1 { get; set; }
        public Nullable<short> LiqDay2 { get; set; }
        public short PaymentDay1 { get; set; }
        public short PaymentDay2 { get; set; }
    
        public virtual ICollection<ProducerCode> ProducerCodes { get; set; }
        public virtual ICollection<CreditCard> CreditCards { get; set; }
        public virtual ICollection<Contact> Contacts { get; set; }
        public virtual ICollection<Risk> Risks { get; set; }
        public virtual ICollection<Liquidation> Liquidations { get; set; }
    }
}
