//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seggu.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coverage
    {
        public Coverage()
        {
            this.Integrals = new HashSet<Integral>();
            this.Employees = new HashSet<Employee>();
            this.Vehicles = new HashSet<Vehicle>();
            this.CoveragesPacks = new HashSet<CoveragesPack>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.Guid RiskId { get; set; }
    
        public virtual ICollection<Integral> Integrals { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<Vehicle> Vehicles { get; set; }
        public virtual Risk Risk { get; set; }
        public virtual ICollection<CoveragesPack> CoveragesPacks { get; set; }
    }
}
