//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seggu.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoveragesPack
    {
        public CoveragesPack()
        {
            this.Coverages = new HashSet<Coverage>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public System.Guid RiskId { get; set; }
    
        public virtual Risk Risk { get; set; }
        public virtual ICollection<Coverage> Coverages { get; set; }
    }
}
