//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seggu.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Coverages = new HashSet<Coverage>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid PolicyId { get; set; }
        public Nullable<System.Guid> EndorseId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string DNI { get; set; }
        public string CUIT { get; set; }
        public Nullable<bool> IsRemoved { get; set; }
        public decimal InsuranceAmount { get; set; }
    
        public virtual Policy Policy { get; set; }
        public virtual Endorse Endorse { get; set; }
        public virtual ICollection<Coverage> Coverages { get; set; }
    }
}
