//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seggu.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fee
    {
        public Fee()
        {
            this.CashAccount = new HashSet<CashAccount>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid PolicyId { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public short Number { get; set; }
        public decimal Value { get; set; }
        public decimal Balance { get; set; }
        public decimal CompanyPayment { get; set; }
        public bool Annulated { get; set; }
        public Nullable<System.Guid> FeeSelectionId { get; set; }
        public FeeState State { get; set; }
        public Nullable<System.Guid> EndorseId { get; set; }
        public string RegisteredLiqDate { get; set; }
    
        public virtual Policy Policy { get; set; }
        public virtual ICollection<CashAccount> CashAccount { get; set; }
        public virtual FeeSelection FeeSelection { get; set; }
        public virtual Endorse Endorse { get; set; }
    }
}
