//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seggu.Data
{
    using System;
    
    public enum FeeState : short
    {
        Debe = 0,
        Pagado = 1,
        Observado = 2,
        Preliquidado = 3,
        Liquidado = 4,
        Mantener_Cubierto = 5,
        Moroso = 6,
        Sin_Cobertura = 7,
        Debe_y_Preliq = 8,
        otro = 9
    }
}
