//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seggu.Data
{
    using System;
    
    public enum IVA : int
    {
        Consumidor_final = 1,
        Resp_Monotributo = 2,
        Resp_Inscripto = 3,
        Resp_No_Inscripto = 4,
        Gran_Contribuyente = 5,
        No_Responsable = 6,
        Exento = 7,
        No_Grabado = 8
    }
}
