//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seggu.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Liquidation
    {
        public Liquidation()
        {
            this.FeeSelections = new HashSet<FeeSelection>();
        }
    
        public System.Guid Id { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Total { get; set; }
        public Nullable<System.DateTime> ReceptionDate { get; set; }
        public bool Registered { get; set; }
        public string Notes { get; set; }
        public System.Guid CompanyId { get; set; }
    
        public virtual ICollection<FeeSelection> FeeSelections { get; set; }
        public virtual Company Company { get; set; }
    }
}
