//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seggu.Data
{
    using System;
    
    public enum MaritalStatus : int
    {
        Soltero = 1,
        Casado = 2,
        Divorciado = 3,
        Viudo = 4,
        Concubino = 5
    }
}
