//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seggu.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producer
    {
        public Producer()
        {
            this.ProducerCodes = new HashSet<ProducerCode>();
            this.CashAccounts = new HashSet<CashAccount>();
            this.Policies = new HashSet<Policy>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string RegistrationNumber { get; set; }
        public bool IsCollector { get; set; }
    
        public virtual ICollection<ProducerCode> ProducerCodes { get; set; }
        public virtual ICollection<CashAccount> CashAccounts { get; set; }
        public virtual ICollection<Policy> Policies { get; set; }
    }
}
