//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seggu.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProducerCode
    {
        public System.Guid ProducerId { get; set; }
        public System.Guid CompanyId { get; set; }
        public string Code { get; set; }
    
        public virtual Producer Producer { get; set; }
        public virtual Company Company { get; set; }
    }
}
