//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seggu.Data
{
    using System;
    
    public enum RiskType : int
    {
        Automotores = 1,
        Combinados_Integrales = 2,
        Vida_colectivo_Otros = 3,
        Vida_individual = 4,
        Otros = 5
    }
}
