//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seggu.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Risk
    {
        public Risk()
        {
            this.CoveragesPacks = new HashSet<CoveragesPack>();
            this.Policy = new HashSet<Policy>();
            this.Coverages = new HashSet<Coverage>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public RiskType RiskType { get; set; }
        public System.Guid CompanyId { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual ICollection<CoveragesPack> CoveragesPacks { get; set; }
        public virtual ICollection<Policy> Policy { get; set; }
        public virtual ICollection<Coverage> Coverages { get; set; }
    }
}
