//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seggu.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public Vehicle()
        {
            this.Accessories = new HashSet<Accessory>();
            this.Coverages = new HashSet<Coverage>();
        }
    
        public System.Guid Id { get; set; }
        public string Plate { get; set; }
        public string Engine { get; set; }
        public string Year { get; set; }
        public string Chassis { get; set; }
        public System.Guid PolicyId { get; set; }
        public Nullable<System.Guid> EndorseId { get; set; }
        public System.Guid VehicleModelId { get; set; }
        public System.Guid UseId { get; set; }
        public System.Guid BodyworkId { get; set; }
        public Nullable<bool> IsRemoved { get; set; }
    
        public virtual ICollection<Accessory> Accessories { get; set; }
        public virtual Policy Policy { get; set; }
        public virtual Endorse Endorse { get; set; }
        public virtual VehicleModel VehicleModel { get; set; }
        public virtual Use Use { get; set; }
        public virtual Bodywork Bodywork { get; set; }
        public virtual ICollection<Coverage> Coverages { get; set; }
    }
}
