//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seggu.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleModel
    {
        public VehicleModel()
        {
            this.Vehicles = new HashSet<Vehicle>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public Origin Origin { get; set; }
        public System.Guid BrandId { get; set; }
        public System.Guid VehicleTypeId { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual VehicleType VehicleType { get; set; }
        public virtual ICollection<Vehicle> Vehicles { get; set; }
    }
}
